### PR TITLE
Rails 4.0, 4.1 and 4.2.0 support

### PR DESCRIPTION
**Pull request by tagliala**
For those interested, my branch works with rails 4.0.12, 4.1.8, 4.2.0

I also fixed an issue with regexp validations.

This branch is based on `3-2-stable` because it contains fixes that weren't "backported" to `4.0-beta`

https://github.com/tagliala/client_side_validations/tree/rails4

### CODE REVIEW

**Comment by Dinuz** [comment]
@tagliala I think you did a great job until now, and I am sure that you built a deep knowledge of the overall gem.

I think you should take over the gem, it's a very good gem, and there aren't other gem around good as this.

**Comment by tagliala** [comment]
thanks @Dinuz 

@bcardarella I'm available (since there is nobody else)

**Comment by bcardarella** [comment]
@tagliala great, I can add you on. Thank you very much for stepping up :)

**Comment by bcardarella** [comment]
@tagliala you're on. Once `master` is all set I can give you rubygems access

**Comment by tagliala** [comment]
@bcardarella you're welcome, I will let you know in the next couple of days.

I will also need access to plugins (turbolinks, simple_form...)

**Comment by tagliala** [comment]
https://travis-ci.org/bcardarella/client_side_validations/builds/47358377
:+1:

**Comment by tagliala** [comment]
@bcardarella I also need to set the default branch to `4-2-stable`, manage pr and issues. Thanks!

**Comment by bcardarella** [comment]
@tagliala for personal projects it doesn't seem that GitHub allows for adding additional owners, just collaborators. I'm going to transfer this project over to @DavyJonesLocker and add you as an owner

**Comment by bcardarella** [comment]
@tagliala you should be all set

**Comment by tagliala** [comment]
screen shot 2015-01-17 at 18 01 19

I cannot see "Settings" here

**Comment by bcardarella** [comment]
@tagliala github says you have a pending invitation... it might be in your email?

**Comment by tagliala** [comment]
thanks, got it in "updates", didn't get the notification sound :+1:

**Pull request closed without merging**
